project:
  type: website
  resources:
    - "*.jpg"
    - "images/**"
  output-dir: docs

website:
  title: "Senthil Sukumar"
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - href: assignment5.qmd
        text: Assignment 5


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

jupyter:
  kernelspec:
    name: venv
    display_name: Python (venv)
    language: python