project:
  type: website
  resources:
    - "*.jpg"
    - "images/**"
  # output-dir: docs

website:
  title: "Senthil Sukumar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assignment1.qmd
        text: Assignment 1
      - href: assignment2.qmd
        text: Assignment 2
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
