[project]
name = "senthilsukumar-bu-github-io"
version = "0.0.1"
description = "Initital website for Senthil Sukumar GitHub"
authors = [
    {name = "Senthil Sukumar",email = "senthils@bu.edu"}
]
readme = "README.md"
requires-python = "^3.13"
dependencies = [
    "numpy (>=2.5.2,<3.0.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "matplotlib (>=3.11.1,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "plotly (>=7.0.0,<8.0.0)"
]

[tool.poetry]
packages = [{include = "senthilsukumar_bu"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
